name: has
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1



environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Sorted alphabetically
  cached_network_image: ^3.4.1
  chat_bubbles: ^1.6.0
  chat_gpt_sdk: ^3.1.5
  clipboard: ^2.0.2
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  firebase_auth: ^6.0.1
  flutter_dotenv: ^5.1.0
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_storage: ^13.0.0
  geolocator: ^14.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.9.0
  google_sign_in: ^7.1.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  open_file: ^3.3.2
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^12.0.1
  printing: ^5.13.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/HAS_LOGO.png"  
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/images/HAS_LOGO.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: TanjimFonts
      fonts:
        - asset: assets/fonts/TanjimFonts.otf
  generate: true      

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Images
    - assets/images/
    # Data files
    - assets/data/
    # Fonts
    - assets/fonts/
    # Environment files
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
  #- asset: fonts/TanjimFonts.otf
  #- family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
      


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
